### ISSUE TITLE
compiling error

### ISSUE THREAD

**Issue by malsvn** [0x676e67/reqwest-impersonate#15]
```
    crypto.vcxproj -> C:\Users\Administrator\Desktop\Scripts\Discord\Freelance\rust-claimer\target\debug\build\boring-sys-imp-f95bce9fa3443951\out\build\Debug\crypto.lib
  cargo:root=C:\Users\Administrator\Desktop\Scripts\Discord\Freelance\rust-claimer\target\debug\build\boring-sys-imp-f95bce9fa3443951\out
  cargo:rustc-link-search=native=C:\Users\Administrator\Desktop\Scripts\Discord\Freelance\rust-claimer\target\debug\build\boring-sys-imp-f95bce9fa3443951\out/build/Debug
  cargo:rustc-link-lib=static=crypto
  cargo:rustc-link-lib=static=ssl
  cargo:rerun-if-env-changed=BORING_BSSL_INCLUDE_PATH

  --- stderr
  thread 'main' panicked at C:\Users\Administrator\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bindgen-0.69.4\lib.rs:622:31:
  Unable to find libclang: "couldn't find any valid shared libraries matching: ['clang.dll', 'libclang.dll'], set the `LIBCLANG_PATH` environment variable to a path where one of these files can be found (invalid: [])"
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
  ```

**Comment by danepoirier0** [comment]
Also encounter similar error. 

OS: Mac Monterey Ver 12.7.5
CPU: Intel 


`--- stderr
  deps/boringssl/src/include/openssl/base.h:61:10: fatal error: 'sys/types.h' file not found
  thread 'main' panicked at /Users/luoqing/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/boring-sys-imp-2.1.0/build.rs:558:39:
  Unable to generate bindings: ClangDiagnostic("deps/boringssl/src/include/openssl/base.h:61:10: fatal error: 'sys/types.h' file not found\n")
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace`

Anyone can help?

**Comment by 0x676e67** [comment]
You need to install the compilation environment of boringssl related platforms, please refer to: https://github.com/google/boringssl/blob/master/BUILDING.md
