### ISSUE TITLE
Using a proxy on MacOS will cause a timeout error

### ISSUE THREAD

**Issue by danepoirier0** [0x676e67/reqwest-impersonate#16]
When I use the code `.proxy(reqwest::Proxy::http("http://localhost:7890")?)` to set a proxy, requesting certain URLs (http://chatgpt.com/) results in a timeout. When I comment out this line (and use the system proxy), I can access chatgpt.com normally.

----
OS: MacOs Monterey Ver 12.7.5
CPU: Intel
reqwest-impersonate Version: 0.11.84
----
 
When I run the code on Ubuntu, it correctly sets the proxy

Here is my codes:
`let client = reqwest::Client::builder()
        .timeout(Duration::from_secs(9))
        .proxy(reqwest::Proxy::http("http://localhost:7890")?)
        .impersonate(Impersonate::Chrome120)
        .danger_accept_invalid_certs(true)
        .enable_ech_grease()
        .permute_extensions()
        .build()?;

let resp = client
        .get("https://chatgpt.com/")
        // .headers(headers)
        .send().await?;
`

**Comment by 0x676e67** [comment]
use `reqwest::Proxy::all`

**Comment by danepoirier0** [comment]
thank you, it worked
