### ISSUE TITLE
Add priority frame to http2

### ISSUE THREAD

**Issue by 0x953** [0x676e67/reqwest-impersonate#17]
With Chromium based browsers, according to https://tls.peet.ws/api/all, reqwest-impersonate is missing the priority frame:
Chromium-based:
```
[...]
        "flags": [
          "EndStream (0x1)",
          "EndHeaders (0x4)",
          "Priority (0x20)"
        ],
        "priority": {
          "weight": 256,
          "depends_on": 0,
          "exclusive": 1
        }
[...]
```

reqwest-impersonate:
```
[...]
        "flags": [
          "EndStream (0x1)",
          "EndHeaders (0x4)"
        ],
[...]
```

Would it be possible to add this frame?

**Comment by 0x676e67** [comment]
Look at the http2 hash calculation. It does not participate in the calculation. In addition, the default priority is not implemented in the upstream repository. If the upstream warehouse catches up with the schedule, I will update it.
