### ISSUE TITLE
Support Ordered Headers

### ISSUE THREAD

**Issue by shrimpyuk** [0x676e67/reqwest-impersonate#18]
Hello!

Is it possible to add support for ordered headers for example https://github.com/ignassew/http-ordered and https://github.com/ignassew/reqwestplus have this feature, but should be definable per request.

**Comment by 0x676e67** [comment]
No plans, I have fixed the request header order for different browsers

**Comment by shrimpyuk** [comment]
> No plans, I have fixed the request header order for different browsers

![CleanShot 2024-06-17 at 11 49 49@2x](https://github.com/0x676e67/reqwest-impersonate/assets/55786013/ea87eae1-e6cf-4f40-b3c3-4d3c87765e57)
![CleanShot 2024-06-17 at 11 50 14@2x](https://github.com/0x676e67/reqwest-impersonate/assets/55786013/9da17e15-6095-4f56-97bb-944a6e5e197d)

The header ordering isn't correct, and this can be a make or break on some sites with strict antibot. Imo this needs to be addressed.

**Comment by 0x676e67** [comment]
You can provide a PR to resolve this issue.

**Comment by shrimpyuk** [comment]
> You can provide a PR to resolve this issue.

only issue is it requires modifying http to allow for this, as seen for example here https://github.com/ignassew/http-ordered/commits/master/ . let's connect and can work out a clean way for this to be implemented, and i can pr this in.

**Comment by 0x676e67** [comment]
Modifying http will affect all downstream

**Comment by shrimpyuk** [comment]
> Modifying http will affect all downstream

that's the only annoying thing. i did it before with crates patches in my own fork of the above mentioned, but it got very out of date quickly. also noticed that h2 headers do not match safari's proper ordering which is m,s,a,p not m,s,p,a
![CleanShot 2024-06-17 at 12 07 38@2x](https://github.com/0x676e67/reqwest-impersonate/assets/55786013/e37dd2b1-5acc-4ba8-83a2-077a01b9b6dc)

**Comment by 0x676e67** [comment]
<img width="1360" alt="image" src="https://github.com/0x676e67/reqwest-impersonate/assets/51810656/69f82670-5cc5-46b9-a1d8-786e417589db">

**Comment by shrimpyuk** [comment]
> <img alt="image" width="1360" src="https://private-user-images.githubusercontent.com/51810656/340229762-69f82670-5cc5-46b9-a1d8-786e417589db.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2MTI1MTgsIm5iZiI6MTcxODYxMjIxOCwicGF0aCI6Ii81MTgxMDY1Ni8zNDAyMjk3NjItNjlmODI2NzAtNWNjNS00NmI5LWExZDgtNzg2ZTQxNzU4OWRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE3VDA4MTY1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ4ZDU5OGU0N2E4ZjFiYzZmOTUwYzg2YThiODZkODExY2FlMjk2ZWEzMGYwN2U1OWU3ODNjOTYxM2Q0YmU3YjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.USCyytGzDl3XcEjuQ9c8Ay5OP5ms_V3Q9HMU4_sj9LU">

that's very interesting, my ja3 is a lot shorter and produced ja4 is different to you on 17.5 as well, this is definitely something to look into as one of our fingerprints is deviating from what it actually should be, or maybe even both of us.

**Comment by 0x676e67** [comment]
I have many Apple devices and their Safari Http2 header order is the same for all of them

**Comment by shrimpyuk** [comment]
My iPhone produces the same ja4 as you but has the h2 headers in a different order too. Same on my iPad. This isn’t a coincidence.

Best Regards,

James Hutchinson

**Comment by shrimpyuk** [comment]
![IMG_4044](https://github.com/0x676e67/reqwest-impersonate/assets/55786013/b0a737a3-38a0-4180-8e0b-c67fe07e1782)
JA4 matches on my iPhone however h2 is m,s,a,p again. tested on my 17.4 ipad which is m,s,a,p too. this is not a coincidence.

**Comment by 0x676e67** [comment]
This is very interesting

**Comment by 0x676e67** [comment]
![image](https://github.com/0x676e67/reqwest-impersonate/assets/51810656/8eebb694-95c2-4811-b4ea-b095faebdd8c)

**Comment by shrimpyuk** [comment]
> This is very interesting

it is indeed. there's a lot to be added to make these requests more 1:1, happy to work with you if you want to reach out to me on telegram @shrimpwtf

**Comment by shrimpyuk** [comment]
iphone 15 pro on ios 17.5, set to chinese language, same fingerprint but m,s,p,a like yours.
iphone 15 pro max, english, m,s,a,p

this can't be a coincidence, this is so strange.

**Comment by shrimpyuk** [comment]
iphone 14, english, 17.5, m,s,p,a

**Comment by 0x676e67** [comment]
If you have a better suggestion for the header order, please put it forward.

**Comment by shrimpyuk** [comment]
> If you have a better suggestion for the header order, please put it forward.

The way I know of solving it is by patching http and using crate patches. It's got pros and cons, but does work.
I have a messy but working example I've done here;

https://github.com/shrimpyuk/reqwestplus
`[patch.crates-io]
hyper = { git = "https://github.com/shrimpyuk/hyperplus.git", branch = "0.14.28-patched" }
http = { git = "https://github.com/shrimpyuk/http-ordered.git" }`

If there's a different way to do this that doesnt involve modifying and patching hyperplus/http, even better.

**Comment by 0x676e67** [comment]
Patching seems to be a better method, and the patch needs to be applied on the user side. If you modify http directly, you must manually convert the request header.

**Comment by 0x676e67** [comment]
The HeaderMap iteration is indeed consistent with the insertion order, but I don’t know how it is sorted when sending the request.
<img width="1079" alt="image" src="https://github.com/0x676e67/reqwest-impersonate/assets/51810656/4fc6f303-40bf-4841-a3cf-4fbb80e806e6">

**Comment by 0x676e67** [comment]
Next, we might consider implementing PSK extension: https://github.com/0x676e67/reqwest-impersonate/issues/4
