### ISSUE TITLE
怎么添加不了包

### ISSUE THREAD

**Issue by mingtianquan** [0x676e67/reqwest-impersonate#21]
报错
stdout :     Updating crates.io index
error: no matching package found
searched package name: `reqwest_impersonate`
perhaps you meant:      reqwest-impersonate
location searched: registry `crates-io`

**Comment by mingtianquan** [comment]
报错error: failed to run custom build command for `boring-sys-imp v2.1.0`

**Comment by 0x676e67** [comment]
You must install the compilation environment required by boringssl upstream

**Comment by mingtianquan** [comment]
boressl 上游所需的编译环境怎么安装啊，我是rust新手

**Comment by 0x676e67** [comment]
https://github.com/google/boringssl/blob/master/BUILDING.md
