### ISSUE TITLE
windows10调试运行加载reqwest-impersonate运行不了。

### ISSUE THREAD

**Issue by mingtianquan** [0x676e67/reqwest-impersonate#24]
windows10下要怎么才能运行。弄几天了还是运行不起来
error: failed to run custom build command for `boring-sys-imp v2.1.0`
能不能出了文档，

**Comment by 0x676e67** [comment]
没有文档，就是按照官方编译环境要求，windows相对来说比Linux麻烦一百倍，你需要安装微软开发工具包的SDK

**Comment by nekomiya-hinata** [comment]
你得安装llvm，cmake，perl，vs生成工具一类的依赖，还要配置环境变量，这些问题问gpt都可以很方便的解决，提供编译时的具体报错信息就行了

**Comment by mingtianquan** [comment]
windows 安装了vs2022 的，用一个包这么麻烦吗？

**Comment by mingtianquan** [comment]
![QQ截图20240628175953](https://github.com/0x676e67/reqwest-impersonate/assets/157282579/df762e79-f023-40d1-9c91-ba756230cf59)

**Comment by mingtianquan** [comment]
编译好了现在又出这个错误。。。。。

**Comment by mingtianquan** [comment]
// Build a client
    let client = ClientBuilder::new()
        .danger_accept_invalid_certs(true)
        .impersonate(Impersonate::Chrome123)
        .enable_ech_grease()
        .permute_extensions()
        .cookie_store(true)
        .build()?;
 代码这里添加了.danger_accept_invalid_certs(true)  可以了

**Comment by mingtianquan** [comment]
能像https://github.com/wangluozhe/requestszh     这个go库一样多弄点示例嘛 对于新手比较友好。

**Comment by 0x676e67** [comment]
我很疑惑，那你为什么不直接去写go，都写rust了已经不存在什么新手说法了
