### ISSUE TITLE
求助，我想调用这个库编译成32位dll

### ISSUE THREAD

**Issue by mingtianquan** [0x676e67/reqwest-impersonate#25]
已经编译过BoringSSL，调试也能正常调试。但是
用cargo build --target=i686-pc-windows-msvc --release
编译报错
  = note:   正在创建库 C:\Users\hai\Desktop\dd\http_test\target\i686-pc-windows-msvc\release\deps\http.dll.lib 和对象 C:\Users\hai\Desktop\dd\http_test\target\i686-pc-windows-msvc\release\deps\http.dll.exp
          libboring_sys_imp-88ab6b72d94b36c3.rlib(bcm.obj) : error LNK2019: 无法解析的外部符号 _aes_hw_set_encrypt_key，函数 _AES_set_encrypt_key 中引用了该符号
          libboring_sys_imp-88ab6b72d94b36c3.rlib(bcm.obj) : error LNK2019: 无法解析的外部符号 _aes_hw_set_decrypt_key，函数 _AES_set_decrypt_key 中引用了该符号
          libboring_sys_imp-88ab6b72d94b36c3.rlib(bcm.obj) : error LNK2019: 无法解析的外部符号 _aes_hw_encrypt，函数 _AES_encrypt 中引用了该符号
          libboring_sys_imp-88ab6b72d94b36c3.rlib(bcm.obj) : error LNK2019: 无法解析的外部符号 _aes_hw_decrypt，函数 _AES_decrypt 中引用了该符号
          libboring_sys_imp-88ab6b72d94b36c3.rlib(bcm.obj) : error LNK2019: 无法解析的外部符号 _aes_hw_cbc_encrypt，函数 _AES_cbc_encrypt 中引用了该符号
          libboring_sys_imp-88ab6b72d94b36c3.rlib(bcm.obj) : error LNK2019: 无法解析的外部符号 _aes_hw_ctr32_encrypt_blocks，函数 _AES_ctr128_encrypt 中引用了该符号
          libboring_sys_imp-88ab6b72d94b36c3.rlib(bcm.obj) : error LNK2019: 无法解析的外部符号 _aes_hw_ecb_encrypt，函数 _aes_hw_ecb_cipher 中引用了该符号
          libboring_sys_imp-88ab6b72d94b36c3.rlib(bcm.obj) : error LNK2019: 无法解析的外部符号 _vpaes_set_encrypt_key，函数 _AES_set_encrypt_key 中引用了该符号
          libboring_sys_imp-88ab6b72d94b36c3.rlib(bcm.obj) : error LNK2019: 无法解析的外部符号 _vpaes_set_decrypt_key，函数 _AES_set_decrypt_key 中引用了该符号
          libboring_sys_imp-88ab6b72d94b36c3.rlib(bcm.obj) : error LNK2019: 无法解析的外部符号 _vpaes_encrypt，函数 _AES_encrypt 中引用了该符号
          libboring_sys_imp-88ab6b72d94b36c3.rlib(bcm.obj) : error LNK2019: 无法解析的外部符号 _vpaes_decrypt，函数 _AES_decrypt 中引用了该符号
          libboring_sys_imp-88ab6b72d94b36c3.rlib(bcm.obj) : error LNK2019: 无法解析的外部符号 _vpaes_cbc_encrypt，函数 _aes_init_key 中引用了该符号
          libboring_sys_imp-88ab6b72d94b36c3.rlib(bcm.obj) : error LNK2019: 无法解析的外部符号 _gcm_init_clmul，函数 _CRYPTO_ghash_init 中引用了该符号
          libboring_sys_imp-88ab6b72d94b36c3.rlib(bcm.obj) : error LNK2019: 无法解析的外部符号 _gcm_gmult_clmul，函数 _CRYPTO_ghash_init 中引用了该符号
          libboring_sys_imp-88ab6b72d94b36c3.rlib(bcm.obj) : error LNK2019: 无法解析的外部符号 _gcm_ghash_clmul，函数 _CRYPTO_ghash_init 中引用了该符号
          libboring_sys_imp-88ab6b72d94b36c3.rlib(bcm.obj) : error LNK2019: 无法解析的外部符号 _gcm_gmult_ssse3，函数 _CRYPTO_ghash_init 中引用了该符号
          libboring_sys_imp-88ab6b72d94b36c3.rlib(bcm.obj) : error LNK2019: 无法解析的外部符号 _gcm_ghash_ssse3，函数 _CRYPTO_ghash_init 中引用了该符号
          libboring_sys_imp-88ab6b72d94b36c3.rlib(bcm.obj) : error LNK2019: 无法解析的外部符号 _bn_mul_add_words，函数 _bn_from_montgomery_in_place 中引用了该符号
          libboring_sys_imp-88ab6b72d94b36c3.rlib(bcm.obj) : error LNK2019: 无法解析的外部符号 _bn_mul_words，函数 _BN_mul_word 中引用了该符号
          libboring_sys_imp-88ab6b72d94b36c3.rlib(bcm.obj) : error LNK2019: 无法解析的外部符号 _bn_sqr_words，函数 _bn_sqr_normal 中引用了该符号
          libboring_sys_imp-88ab6b72d94b36c3.rlib(bcm.obj) : error LNK2019: 无法解析的外部符号 _bn_add_words，函数 _BN_div 中引用了该符号
          libboring_sys_imp-88ab6b72d94b36c3.rlib(bcm.obj) : error LNK2019: 无法解析的外部符号 _bn_sub_words，函数 _BN_div 中引用了该符号
          libboring_sys_imp-88ab6b72d94b36c3.rlib(bcm.obj) : error LNK2019: 无法解析的外部符号 _bn_mul_comba4，函数 _bn_mul_recursive 中引用了该符号
          libboring_sys_imp-88ab6b72d94b36c3.rlib(bcm.obj) : error LNK2019: 无法解析的外部符号 _bn_mul_comba8，函数 _bn_mul_small 中引用了该符号
          libboring_sys_imp-88ab6b72d94b36c3.rlib(bcm.obj) : error LNK2019: 无法解析的外部符号 _bn_sqr_comba8，函数 _bn_sqr_consttime 中引用了该符号
          libboring_sys_imp-88ab6b72d94b36c3.rlib(bcm.obj) : error LNK2019: 无法解析的外部符号 _bn_sqr_comba4，函数 _bn_sqr_consttime 中引用了该符号
          libboring_sys_imp-88ab6b72d94b36c3.rlib(bcm.obj) : error LNK2019: 无法解析的外部符号 _bn_mul_mont，函数 _BN_mod_mul_montgomery 中引用了该符号
          libboring_sys_imp-88ab6b72d94b36c3.rlib(bcm.obj) : error LNK2019: 无法解析的外部符号 _md5_block_asm_data_order，函数 _MD5_Update 中引用了该符号
          libboring_sys_imp-88ab6b72d94b36c3.rlib(bcm.obj) : error LNK2019: 无法解析的外部符号 _sha1_block_data_order，函数 _SHA1_Update 中引用了该符号
          libboring_sys_imp-88ab6b72d94b36c3.rlib(bcm.obj) : error LNK2019: 无法解析的外部符号 _sha256_block_data_order，函数 _SHA256_Update 中引用了该符号
          libboring_sys_imp-88ab6b72d94b36c3.rlib(bcm.obj) : error LNK2019: 无法解析的外部符号 _sha512_block_data_order，函数 _SHA512_Update 中引用了该符号
          libboring_sys_imp-88ab6b72d94b36c3.rlib(chacha.obj) : error LNK2019: 无法解析的外部符号 _ChaCha20_ctr32，函数 _CRYPTO_chacha_20 中引用了该符号
          C:\Users\hai\Desktop\dd\http_test\target\i686-pc-windows-msvc\release\deps\http.dll : fatal error LNK1120: 32 个无法解析的外部命令
![Uploading QQ截图20240702030241.png…]()

**Comment by mingtianquan** [comment]
编译cargo build --release  能编译通过。

**Comment by 0x676e67** [comment]
sorry，我不用window
