### ISSUE TITLE
请问这个库和rust的reqwest 有哪些区别？

### ISSUE THREAD

**Issue by 1500256797** [0x676e67/reqwest-impersonate#26]
最近也在研究reqwest 修改ja3，偶然间发现了这个库，请问reqwest是因为不支持修改ja3，所以你才重新创立了这个crate？ 能否告诉下原因。谢谢

**Comment by 0x676e67** [comment]
yes，闲的无聊可以来研究实现这个扩展：https://github.com/0x676e67/reqwest-impersonate/issues/4

**Comment by 1500256797** [comment]
我邮箱联系你
