### ISSUE TITLE
Windows 下编译使用

### ISSUE THREAD

**Issue by 1500256797** [0x676e67/reqwest-impersonate#33]
Windows 下编译确实很费劲 

花了我整个周末

不过我已经解决了 

为了帮助更多的人减少时间浪费

有问题可联系我

**Comment by deedy5** [comment]
Do you mean `nasm`?
https://github.com/deedy5/pyreqwest_impersonate/blob/0b80d7fb4b2bee39b02a4fb2ebfff85c85c33fad/.github/workflows/CI.yml#L143-L144

**Comment by 1500256797** [comment]
> Do you mean `nasm`? https://github.com/deedy5/pyreqwest_impersonate/blob/0b80d7fb4b2bee39b02a4fb2ebfff85c85c33fad/.github/workflows/CI.yml#L143-L144

no i mean i spent a lot time to build this crate on the windows10 , so if you need help , pls contact me
