### ISSUE TITLE
BoringSSL PSK extension for Chrome123/Chrome126

### ISSUE THREAD

**Issue by 0x676e67** [0x676e67/reqwest-impersonate#4]
reference: https://tls.peet.ws/api/all

**Comment by cxw620** [comment]
Like this?
![image](https://github.com/user-attachments/assets/1ea21c79-87d1-4cbe-8013-a479ce58829a)

**Comment by 0x676e67** [comment]
this <img width="1549" alt="image" src="https://github.com/user-attachments/assets/b300bcfd-76fb-4e80-b267-e6368c034383">

**Comment by 0x676e67** [comment]
ref: https://github.com/cloudflare/boring/blob/8786cda63958fe1376537c52f3c7e6bdfc02d933/boring/src/ssl/test/mod.rs#L840

**Comment by 0x676e67** [comment]
The first request will not have an extension, and the second request will have a pre_share_key extension, provided that the browser maintains keepalive. If you switch to incognito mode, it will disappear.

**Comment by cxw620** [comment]
I didn't find it, an ab testing feature? My browser: Chrome 126.0.6478.182

**Comment by 0x676e67** [comment]
Refresh the second time

**Comment by cxw620** [comment]
Ok got it. Investigating.

**Comment by 0x676e67** [comment]
The current situation is that setting the psk callback does not work, and the callback is not even triggered.

**Comment by cxw620** [comment]
~~should we reuse hyper_boring::HttpsLayer for internal cache of tls session?~~ maybe we have to checkout boringssl's source code... don't know and try to investigate why callback is not even triggered.

**Comment by cxw620** [comment]
Emmm, really easy to do so...

```
let _ = unsafe { boring_sys::SSL_CTX_use_psk_identity_hint(builder.as_ptr(), "client_hint_1".as_ptr() as _) };

```

We may provide psk identity hint and probably also reuse hyper_boring::HttpsLayer...

**Comment by 0x676e67** [comment]
cool

**Comment by 0x676e67** [comment]
<img width="984" alt="image" src="https://github.com/user-attachments/assets/8f56a29e-1fe3-4b3b-b2cb-c021237924a6">

**Comment by 0x676e67** [comment]
If possible, you can simply PR now and I will see if there is a way to cache TLS sessions or something like that.

**Comment by 0x676e67** [comment]
It doesn't seem to work, can you provide an example?
<img width="1048" alt="image" src="https://github.com/user-attachments/assets/7eee84a4-dde2-44bf-9d86-629f0a9a8212">

**Comment by cxw620** [comment]
> It doesn't seem to work, can you provide an example?

Have u reused httpsconnector(although should not do so but httpslayer, for every time we connect to dest httpconnector may have different conf)? Or it will create a new tls session cache each time u create a httpsconnector, see `hyper-boring`'s source code, here and here:

![image](https://github.com/user-attachments/assets/f1f7d87b-8222-429c-99ac-90668ccba280)

![image](https://github.com/user-attachments/assets/9030fa24-a549-493f-a0ec-fb62b744c09c)

This is my temporary solution that tested in my own proj:

![image](https://github.com/user-attachments/assets/e54a41e5-97d8-424b-9217-8d711ff51d88)

I mainly work on my own fork version of `reqwest` and `boring` series for hyper v1 upgrade, removing unnecessary parts, etc (although special thanks to your work!), so I could just provide my idea here instead of PR :)

I'm investigating Chromium's source code now to find out how Chromium deals with psk identity hint.

**Comment by 0x676e67** [comment]
What's interesting is that I didn't set any psk callbacks, it seems to be supported by default. I don't know if there is a problem with the patch I used.
<img width="1724" alt="image" src="https://github.com/user-attachments/assets/81fc3e81-5fbc-44fb-a3b9-7f27ebe458b8">

**Comment by cxw620** [comment]
> What's interesting is that I didn't set any psk callbacks, it seems to be supported by default. I don't know if there is a problem with the patch I used. <img alt="image" width="1724" src="https://private-user-images.githubusercontent.com/51810656/352453158-81fc3e81-5fbc-44fb-a3b9-7f27ebe458b8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5ODI1NjQsIm5iZiI6MTcyMTk4MjI2NCwicGF0aCI6Ii81MTgxMDY1Ni8zNTI0NTMxNTgtODFmYzNlODEtNWZiYy00NGZiLWEzYjktN2YyN2ViZTQ1OGI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI2VDA4MjQyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVlYzQ4OGJmYTVjZjg3MTJhZThkZTA4MWRhYThkNjBkYTk0MDAxZTdkMWFmMmM5MWVkMmZhMDJiOGEzZWZlZjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.48lKLsLRDhS4RGg24KWJjETMQxuwvcpvA3Obx9lUY1U">

I think it is supported by default, for I just upgrade hyper to v1 and everything works. I wiresharked and confirmed that psk is from NewSessionTicket as it should be.

**Comment by 0x676e67** [comment]
This matter has come to an end for now. The http2 header default priority of rust has not been implemented. Are you interested in studying it?
https://github.com/0x676e67/reqwest-impersonate/issues/48

**Comment by cxw620** [comment]
For SSL_set_psk_client_callback or SSL_CTX_set_psk_client_callback, they are for TLS 1.2 and called only when client sends SKE in TLS 1.3. I think that's why it 's not triggered.

**Comment by 0x676e67** [comment]
But in fact, TLS1.3 is generally used by default. I think this problem has been solved. TLS1.3 no longer needs to be manually set.

**Comment by 0x676e67** [comment]
Cloudflare CDN and AWS CDN both use TLS 1.3 as the highest level by default

**Comment by cxw620** [comment]
> This matter has come to an end for the time being. The http2 header default priority of rust has not been implemented. Are you interested in studying it together? #48

Emmm, I know little about http2... I may spare some of my free time doing so.

**Comment by 0x676e67** [comment]
For some connections through proxy tunnel, there is no session processing, and SessionCache does not even have pub, which is troublesome.

**Comment by 0x676e67** [comment]
For some connections through the proxy tunnel, there is no session processing, and SessionCache does not even have pub, so the solution seems a bit troublesome

**Comment by cxw620** [comment]
To be honest, no need to set hint, just reuse the inner session cache... Emmm why did hyper-boring not use oncecell...

**Comment by 0x676e67** [comment]
For proxy not working, I got the configura from https connector and set the callback
https://github.com/0x676e67/reqwest-impersonate/blob/61c605531881215c8ab95f8eda557969c7d6d6fb/src/connect.rs#L316

**Comment by 0x676e67** [comment]
How do you think it should be written?

**Comment by cxw620** [comment]
> How do you think it should be written?

code snip for u to copy from, details above:

```rust
        static CACHE: OnceLock<Arc<Mutex<SessionCache>>> = OnceLock::new();

        let cache = CACHE
            .get_or_init(|| {
                Arc::new(Mutex::new(SessionCache::with_capacity(
                    settings.session_cache_capacity,
                )))
            })
            .clone();

        {
            cache
                .lock()
                .set_session_cache_capacity(settings.session_cache_capacity);
        }
```

```rust
    pub fn set_session_cache_capacity(&mut self, capacity: usize) {
        self.per_key_session_capacity = capacity;
    }

```

**Comment by 0x676e67** [comment]
No, I mean how do you solve it when using Socks5 proxy?
<img width="1236" alt="image" src="https://github.com/user-attachments/assets/146ca9a4-15e0-4e81-9e7d-9eb33bace718">

**Comment by cxw620** [comment]
> No, I mean how do you solve it when using Socks5 proxy? <img alt="image" width="1236" src="https://private-user-images.githubusercontent.com/51810656/352510939-146ca9a4-15e0-4e81-9e7d-9eb33bace718.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5OTI4NDQsIm5iZiI6MTcyMTk5MjU0NCwicGF0aCI6Ii81MTgxMDY1Ni8zNTI1MTA5MzktMTQ2Y2E5YTQtMTVlMC00ZTgxLTllN2QtOWViMzNiYWNlNzE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI2VDExMTU0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFiNmJmNzc0ZTU2YTk0YTU1N2UyYzQ2NzM2NTRlOGIyNzI4YjhhZGRiNmY4NTJjMWNkYjY0MzQxZDE4MmU3NmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.s05dfZRUXadQKVNCBVJV_wBTq1p2mZC6WeTEXRMcXCA">

let me see

**Comment by 0x676e67** [comment]
The https connector has a session cache already set up, just clone it

**Comment by cxw620** [comment]
> The https connector has a session cache already set up, just clone it

yep, we may add a conf to hyper-boring telling it we manage sessions manually.
