### ISSUE TITLE
Compiler errors when enabling tls features

### ISSUE THREAD

**Issue by deedy5** [0x676e67/reqwest-impersonate#7]
### How to reproduce the problem:

https://github.com/gngpp/reqwest-impersonate/blob/67ce1ec25cdb93b99f1b5c2d8ba4547c4977de67/Cargo.toml#L24-L25

Add `default-tls` or `native-tls` or `rustls-tls` to default:
```rust
[features]
default = ["boring-tls", "impersonate", "rustls-tls"]
```

**Comment by gngpp** [comment]
This library is only suitable for boring tls.

**Comment by gngpp** [comment]
To use other tls, you need to turn off the default features. And the compilation may fail. If you have time to fix it, please pr
